<?xml version="1.0" encoding="UTF-8"?><testrun name="BlogTestCase" project="CollaborationBackEnd" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="com.niit.CollaborationBackEnd.testCase.BlogTestCase" time="0.666">
    <testcase name="createBlogTestCase" classname="com.niit.CollaborationBackEnd.testCase.BlogTestCase" time="0.339"/>
    <testcase name="getAllBlogsTestCase" classname="com.niit.CollaborationBackEnd.testCase.BlogTestCase" time="0.327">
      <failure>java.lang.AssertionError: getAllUsersTestCase expected:&lt;8&gt; but was:&lt;10&gt;&#13;
	at org.junit.Assert.fail(Assert.java:69)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:329)&#13;
	at org.junit.Assert.assertEquals(Assert.java:97)&#13;
	at com.niit.CollaborationBackEnd.testCase.BlogTestCase.getAllBlogsTestCase(BlogTestCase.java:80)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.junit.internal.runners.TestMethodRunner.executeMethodBody(TestMethodRunner.java:99)&#13;
	at org.junit.internal.runners.TestMethodRunner.runUnprotected(TestMethodRunner.java:81)&#13;
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)&#13;
	at org.junit.internal.runners.TestMethodRunner.runMethod(TestMethodRunner.java:75)&#13;
	at org.junit.internal.runners.TestMethodRunner.run(TestMethodRunner.java:45)&#13;
	at org.junit.internal.runners.TestClassMethodsRunner.invokeTestMethod(TestClassMethodsRunner.java:75)&#13;
	at org.junit.internal.runners.TestClassMethodsRunner.run(TestClassMethodsRunner.java:36)&#13;
	at org.junit.internal.runners.TestClassRunner$1.runUnprotected(TestClassRunner.java:42)&#13;
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)&#13;
	at org.junit.internal.runners.TestClassRunner.run(TestClassRunner.java:52)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
